### ISSUE TITLE
[Bug] conformer encoder 模型 slim 后无法推理，slim 前正常

### ISSUE THREAD

**Issue by sean-wade** [tsingmicro-toolchain/OnnxSlim#13]
slim优化的截图：
![encoder_slim](https://github.com/tsingmicro-toolchain/OnnxSlim/assets/42532862/2a9bc44d-b9dc-4962-a348-fc33a3a77ad6)

onnxruntime 推理结果截图：
![encoder_issue](https://github.com/tsingmicro-toolchain/OnnxSlim/assets/42532862/62f64fc9-5548-4fbe-8443-43f42c82c157)

**Comment by inisis** [comment]
Hi, this is a bug on latest release, you can pass --skip_fusion_patterns EliminationSlice to avoid this, and I will fix it soon.
