### ISSUE TITLE
When quantizing the Paddle‘s RT-DETR model  , an error occurs during pruning due to the Pad operator.

### ISSUE THREAD

**Issue by ZXB6** [tsingmicro-toolchain/OnnxSlim#31]
![1725613147500](https://github.com/user-attachments/assets/34decd86-a95c-4b82-9f91-65607c15b434)
![1725613173939](https://github.com/user-attachments/assets/726b57fe-7b57-455b-8226-4a3cd3b55cfe)

**Comment by inisis** [comment]
Hi, sorry for the bug, and I think this bug is already fixed, can you try
```
pip install git+https://github.com/inisis/OnnxSlim@main
```
