### ISSUE TITLE
[Bug] 模型转换后无法进行正常推理

### ISSUE THREAD

**Issue by suzhou3772** [tsingmicro-toolchain/OnnxSlim#6]
![Uploading 微信图片_20240312104039.png…]()  
  sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from android_final.onnx failed:This is an invalid model. In Node, ("fusiongelu_12", Gelu, "", -1) : ("/blocks.0/mlp/fc1/Add_output_0": tensor(float),) -> ("/blocks.0/mlp/act/Mul_1_output_0": tensor(float),) , Error No Op registered for Gelu with domain_version of 12

**Comment by inisis** [comment]
Hi, the onnxruntime installed does not support Gelu operator, you can add --skip_fusion_patterns FusionGelu to skip Gelu fusion
